runtime: python27
api_version: 1
threadsafe: true
skip_files:
- ^node_modules/.*
- ^[^w]*semantic/.*

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)

- url: /semantic/(.*)
  static_files: www/semantic\1
  upload: www/semantic/(.*)
  http_headers:
    Access-Control-Allow-Origin: "*"

